trigger:
  - main
  - master
  - develop

pool:
  vmImage: "ubuntu-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"
  dotnetVersion: "8.0.x"
  projectName: "Déduplication Web Application"

stages:
  - stage: Build
    displayName: "Build and Test"
    jobs:
      - job: Build
        steps:
          - task: UseDotNet@2
            inputs:
              version: $(dotnetVersion)
              includePreviewVersions: false

          - task: DotNetCoreCLI@2
            displayName: "Restore NuGet packages"
            inputs:
              command: "restore"
              projects: "$(solution)"
              feedsToUse: "select"
              vstsFeed: "default"

          - task: DotNetCoreCLI@2
            displayName: "Build"
            inputs:
              command: "build"
              projects: "$(solution)"
              arguments: "--configuration $(buildConfiguration) --no-restore"

          - task: DotNetCoreCLI@2
            displayName: "Run Tests"
            inputs:
              command: "test"
              projects: "**/*[Tt]ests/*.csproj"
              arguments: "--configuration $(buildConfiguration) --no-build"
              publishTestResults: true

          - task: DotNetCoreCLI@2
            displayName: "Publish"
            inputs:
              command: "publish"
              publishWebProjects: true
              arguments: "--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
              zipAfterPublish: true

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifacts"
            inputs:
              pathToPublish: "$(Build.ArtifactStagingDirectory)"
              artifactName: "drop"

  - stage: Deploy_Development
    displayName: "Deploy to Development"
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - deployment: Deploy
        environment: "development"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: "tunisia-interns-azure-connection"
                    appName: "$(WebAppName)-dev"
                    package: "$(System.ArtifactsDirectory)/**/*.zip"
                    runtimeStack: "DOTNETCORE|8.0"

  - stage: Deploy_Production
    displayName: "Deploy to Production"
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: Deploy
        environment: "production"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: "current"
                    downloadType: "single"
                    artifactName: "drop"
                    downloadPath: "$(System.ArtifactsDirectory)"

                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: "tunisia-interns-azure-connection"
                    appName: "$(WebAppName)-prod"
                    package: "$(System.ArtifactsDirectory)/**/*.zip"
                    runtimeStack: "DOTNETCORE|8.0"
